Ext.define('StreetsEditor.store.Streets', {
    extend: 'Ext.data.Store',
    alias: 'store.streets',
    storeId: 'Streets',
    autoLoad: true,
    model: 'StreetsEditor.model.Street',
    data: [
        {id: 1, name: 'Тверская', houses: 150, companyId: 1, cityId: 1},
        {id: 2, name: 'Арбат', houses: 89, companyId: 4, cityId: 1},
        {id: 3, name: 'Невский проспект', houses: 210, companyId: 3, cityId: 2},
        {id: 4, name: 'Лиговский проспект', houses: 120, companyId: 4, cityId: 2},
        {id: 5, name: 'Красный проспект', houses: 95, companyId: 1, cityId: 3},
        {id: 6, name: 'Ленина', houses: 78, companyId: 1, cityId: 4},
        {id: 7, name: 'Проспект Победы', houses: 112, companyId: 1, cityId: 5},
        {id: 8, name: 'Баумана', houses: 64, companyId: 5, cityId: 5},
        {id: 9, name: 'Мира', houses: 83, companyId: 2, cityId: 6},
        {id: 10, name: 'Советская', houses: 91, companyId: 5, cityId: 7},
        {id: 11, name: 'Кирова', houses: 67, companyId: 6, cityId: 8},
        {id: 12, name: 'Проспект Карла Маркса', houses: 102, companyId: 7, cityId: 9},
        {id: 13, name: 'Большая Садовая', houses: 145, companyId: 8, cityId: 10},
        {id: 14, name: 'Ленинградская', houses: 88, companyId: 9, cityId: 11},
        {id: 15, name: 'Проспект Металлургов', houses: 76, companyId: 10, cityId: 12},
        {id: 16, name: 'Московский проспект', houses: 134, companyId: 11, cityId: 13},
        {id: 17, name: 'Комсомольский проспект', houses: 98, companyId: 12, cityId: 14},
        {id: 18, name: 'Проспект Ленина', houses: 121, companyId: 13, cityId: 15},
        {id: 19, name: 'Красная', houses: 156, companyId: 14, cityId: 16},
        {id: 20, name: 'Чапаева', houses: 72, companyId: 15, cityId: 17},
        {id: 21, name: 'Республики', houses: 113, companyId: 1, cityId: 18},
        {id: 22, name: 'Ленинградское шоссе', houses: 94, companyId: 2, cityId: 19},
        {id: 23, name: 'Пушкинская', houses: 69, companyId: 3, cityId: 20},
        {id: 24, name: 'Проспект Строителей', houses: 87, companyId: 4, cityId: 21},
        {id: 25, name: 'Гончарова', houses: 59, companyId: 5, cityId: 22},
        {id: 26, name: 'Дзержинского', houses: 104, companyId: 6, cityId: 23},
        {id: 27, name: 'Муравьева-Амурского', houses: 81, companyId: 7, cityId: 24},
        {id: 28, name: 'Свободы', houses: 77, companyId: 8, cityId: 25},
        {id: 29, name: 'Светланская', houses: 92, companyId: 9, cityId: 26},
        {id: 30, name: 'Дахадаева', houses: 63, companyId: 10, cityId: 27},
        {id: 31, name: 'Герцена', houses: 85, companyId: 11, cityId: 28},
        {id: 32, name: 'Советская Армии', houses: 71, companyId: 12, cityId: 29},
        {id: 33, name: 'Весенняя', houses: 66, companyId: 13, cityId: 30},
        {id: 34, name: 'Кутузова', houses: 109, companyId: 14, cityId: 31},
        {id: 35, name: 'Соборная', houses: 78, companyId: 15, cityId: 32},
        {id: 36, name: 'Адмирала Нахимова', houses: 96, companyId: 1, cityId: 33},
        {id: 37, name: 'Проспект Чуйкова', houses: 115, companyId: 2, cityId: 34},
        {id: 38, name: 'Московское шоссе', houses: 124, companyId: 3, cityId: 35},
        {id: 39, name: 'Зеленая', houses: 52, companyId: 4, cityId: 36},
        {id: 40, name: 'Октябрьская', houses: 137, companyId: 5, cityId: 37},
        {id: 41, name: 'Энтузиастов', houses: 89, companyId: 6, cityId: 38},
        {id: 42, name: 'Проспект Димитрова', houses: 101, companyId: 7, cityId: 39},
        {id: 43, name: 'Ленинградское шоссе', houses: 83, companyId: 8, cityId: 40},
        {id: 44, name: 'Красноармейская', houses: 97, companyId: 9, cityId: 41},
        {id: 45, name: 'Дружбы', houses: 74, companyId: 10, cityId: 42},
        {id: 46, name: 'Школьная', houses: 61, companyId: 11, cityId: 43},
        {id: 47, name: 'Магнитогорская', houses: 118, companyId: 12, cityId: 44},
        {id: 48, name: 'Вагжанова', houses: 90, companyId: 13, cityId: 45},
        {id: 49, name: 'Ленина', houses: 142, companyId: 14, cityId: 46},
        {id: 50, name: 'Тагильская', houses: 105, companyId: 15, cityId: 47},
        {id: 51, name: 'Губкина', houses: 79, companyId: 1, cityId: 48},
        {id: 52, name: 'Воскресенская', houses: 86, companyId: 2, cityId: 49},
        {id: 53, name: 'Большая Московская', houses: 153, companyId: 3, cityId: 50},
        {id: 54, name: 'Курортный проспект', houses: 168, companyId: 4, cityId: 51},
        {id: 55, name: 'Жукова', houses: 72, companyId: 5, cityId: 52},
        {id: 56, name: 'Гоголя', houses: 68, companyId: 6, cityId: 53},
        {id: 57, name: 'Театральная', houses: 84, companyId: 7, cityId: 54},
        {id: 58, name: 'Амурская', houses: 99, companyId: 8, cityId: 55},
        {id: 59, name: 'Левый берег', houses: 110, companyId: 9, cityId: 56},
        {id: 60, name: 'Фонтанная', houses: 91, companyId: 10, cityId: 57},
        {id: 61, name: 'Металлургов', houses: 126, companyId: 11, cityId: 58},
        {id: 62, name: 'Мира', houses: 103, companyId: 12, cityId: 59},
        {id: 63, name: 'Ленинградская', houses: 117, companyId: 13, cityId: 60},
        {id: 64, name: 'Кутузовский проспект', houses: 195, companyId: 1, cityId: 1},
        {id: 65, name: 'Садовое кольцо', houses: 300, companyId: 2, cityId: 1},
        {id: 66, name: 'Васильевский остров', houses: 178, companyId: 3, cityId: 2},
        {id: 67, name: 'Большой проспект В.О.', houses: 145, companyId: 4, cityId: 2},
        {id: 68, name: 'Ильича', houses: 82, companyId: 5, cityId: 3},
        {id: 69, name: 'Малышева', houses: 107, companyId: 6, cityId: 4},
        {id: 70, name: 'Декабристов', houses: 93, companyId: 7, cityId: 5},
        {id: 71, name: 'Проспект Аль-Фараби', houses: 132, companyId: 8, cityId: 6},
        {id: 72, name: 'Комарова', houses: 75, companyId: 9, cityId: 7},
        {id: 73, name: 'Цвиллинга', houses: 88, companyId: 10, cityId: 8},
        {id: 74, name: 'Победы', houses: 154, companyId: 11, cityId: 9},
        {id: 75, name: 'Стачек', houses: 119, companyId: 12, cityId: 10},
        {id: 76, name: 'Проспект Октября', houses: 141, companyId: 13, cityId: 11},
        {id: 77, name: 'Урицкого', houses: 95, companyId: 14, cityId: 12},
        {id: 78, name: '9 Января', houses: 80, companyId: 15, cityId: 13},
        {id: 79, name: 'Сибирская', houses: 112, companyId: 1, cityId: 14},
        {id: 80, name: 'Рабоче-Крестьянская', houses: 97, companyId: 2, cityId: 15},
        {id: 81, name: 'Северная', houses: 64, companyId: 3, cityId: 16},
        {id: 82, name: 'Чернышевского', houses: 101, companyId: 4, cityId: 17},
        {id: 83, name: 'Мельникайте', houses: 86, companyId: 5, cityId: 18},
        {id: 84, name: 'Юбилейная', houses: 73, companyId: 6, cityId: 19},
        {id: 85, name: 'Воровского', houses: 89, companyId: 7, cityId: 20},
        {id: 86, name: 'Пролетарская', houses: 122, companyId: 8, cityId: 21},
        {id: 87, name: 'Железнодорожная', houses: 108, companyId: 9, cityId: 22},
        {id: 88, name: 'Трактовая', houses: 134, companyId: 10, cityId: 23},
        {id: 89, name: 'Ангарская', houses: 91, companyId: 11, cityId: 24},
        {id: 90, name: 'Солнечная', houses: 77, companyId: 12, cityId: 25}
    ],
    proxy: {
        type: 'memory',
        reader: {
            type: 'json'
        }
    }
});